### ISSUE TITLE
remove passwords from web.config

### ISSUE THREAD

**Issue by efekthalo** [efekthalo/SiiTaxi#147]

**Comment by efekthalo** [comment]
I don't know how to approach this - I've tried googling for how to encrypt the password on web deploy and found nothing I could use.

@polishere any ideas?

**Comment by polishere** [comment]
I think we don't need to remove passwords from deploy, we need to change credentials and remove them from the repository.

**Comment by efekthalo** [comment]
no need to remove the passwords we have from this repository, these are only temporary and I dont care about them 😃
