### ISSUE TITLE
add some features to table

### ISSUE THREAD

**Issue by polishere** [efekthalo/SiiTaxi#171]
select columns to display, multidelete, etc.   Please add in comment some proposals

**Comment by efekthalo** [comment]
multidelete seems like an overkill so let's not do it, at least for now
selecting columns based on buttons? hide/unhide column

**Comment by polishere** [comment]
now it's dropdown with checkboxes to display columns

**Comment by efekthalo** [comment]
it's ok, however are these settings saved somewhere?

**Comment by polishere** [comment]
no

**Comment by polishere** [comment]
it will be save in cookie https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/cookie.html

**Comment by efekthalo** [comment]
close issue if it's done
