### ISSUE TITLE
Change model of Taxi

### ISSUE THREAD

**Issue by polishere** [efekthalo/SiiTaxi#29]
model changes required:
Change "Other" to list of People
add ownerConfirmation boolean field
add approverConfirmation boolean field
add taxiOrdered boolean field
add string TaxiCode field

**Comment by efekthalo** [comment]
Other is already a list of People - there's a table that does not shown in the model TaxiPeople that stores that kind of data
And I dont think we should store taxi codes - need to be discussed with Emilia I think
