### ISSUE TITLE
recaptcha too strict

### ISSUE THREAD

**Issue by efekthalo** [efekthalo/SiiTaxi#41]
I dont want to click trees or road signs everytime I do something, make it less strict

**Comment by polishere** [comment]
Hmm... It's standard google recaptcha. It's not asking for clicking these things every time, only if it's not sure it's clicked by the human. I've been asked for extra notification always on chrome, but on firefox never.  I found information that it use cookies and IP to recognize the user. I think that it should be that it is. If it will be tiring I can change this later.

**Comment by efekthalo** [comment]
maybe it was just these few times, I tried now and it was ok, lets leave the issue open for now and see how it goes
