### ISSUE TITLE
Different confirmation codes for owner and approver

### ISSUE THREAD

**Issue by polishere** [efekthalo/SiiTaxi#70]
Owner and Approver should receive different messages. Using the same mail and code and owner confirm taxi, it will be equals to approver's confirmation. Also add two new columns to table in the database: confimration code for approver and isConfirmedByApprover

**Comment by efekthalo** [comment]
For the moment lets stick to single confirmation. Both owner and approver receive the email because both can confirm it with the same link. If there really is a business need for confirmation from approver we will implement it.
